"""init migrations

Revision ID: 31feb750c54c
Revises: 
Create Date: 2024-07-03 16:11:05.851787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31feb750c54c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otp_activity',
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('activity_type', sa.String(length=20), nullable=True),
    sa.Column('attempt', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otp_activity_id'), 'otp_activity', ['id'], unique=False)
    op.create_table('otp_list',
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('otp_code', sa.String(length=20), nullable=True),
    sa.Column('expired_time', sa.DateTime(), nullable=True),
    sa.Column('is_used', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otp_list_id'), 'otp_list', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_otp_list_id'), table_name='otp_list')
    op.drop_table('otp_list')
    op.drop_index(op.f('ix_otp_activity_id'), table_name='otp_activity')
    op.drop_table('otp_activity')
    # ### end Alembic commands ###
